version: '3.7'

services:
    bot:
        container_name: TG-Bot-SmolSchool
        image: tg-bot-smolschool

        build:
            dockerfile: Dockerfile
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - .:/app
